[network_params]
latent_neurons = 50
output_neurons = 13

[weight_params]
p = 0.2
q = 0.15
p0 = 0.04
sparsity = 0.3
W_out_out = [0, 0.5]
W_out_lat = [0, 0.5]
W_lat_lat = [0, 0.5]
W_lat_out = [0, 0.5]

[simulation_params]
input = 'test'
dt = 0.01
training_cycles = 10^4
replay_cycles = 100
validation_interval = 20
eta_out = 10^-4
eta_lat = 10^-3

[neuron_params]
C_v = 1.0
C_u = 1.0
E_l = -70.0
E_e = 0.0
E_i = -75.0
g_l = 0.1
g_d = 2.0
g_e = 0.3
g_i = 6.0
a   = 0.3
b   = -58.0
d_d = [5, 15]
d_s = [5, 15]
d_t = 25
