seed = 69

[network_params]
num_lat = 50
num_vis = 13

[weight_params]
w_som_seed = 42
w_den_seed = 99
d_som_seed = 42
d_den_seed = 99
p = 0.5
q = 0.3
p0 = 0.1
den_spars = 0.3
W_vis_vis = [0.0, 0.5]
W_vis_lat = [0.0, 0.5]
W_lat_lat = [0.0, 0.5]
W_lat_vis = [0.0, 0.5]
d_den = [5, 15]
d_som = [5, 15]
d_int = 25

[simulation_params]
input = 'test'
dt = 0.01
pattern_dt = 0.25
training_cycles = 1000
validation_cycles = 1
replay_cycles = 100
validation_interval = 20
eta_out = 10e-4
eta_lat = 10e-3

[neuron_params]
C_v = 1.0
C_u = 1.0
E_l = -70.0
E_exc = 0.0
E_inh = -75.0
g_l = 0.1
g_den = 2.0
g_exc_0 = 0.3
g_inh_0 = 6.0
a   = 0.3
b   = -58.0
lam = 0.6

[data_params]
pattern_length = 22
