seed = 69

[network_params]
num_lat = 50
num_vis = 13

[weight_params]
p = 0.5
q = 0.3
p0 = 0.1
som_seed = 77
den_seed = 42
den_spars = 0.3
W_vis_vis = [0.0, 0.5]
W_vis_lat = [0.0, 0.5]
W_lat_lat = [0.0, 0.5]
W_lat_vis = [0.0, 0.5]
d_den = [5, 15]
d_som = [5, 15]

[simulation_params]
input = 'test'
dt = 0.01
training_cycles = 10e4
replay_cycles = 100
validation_interval = 20
eta_out = 10e-4
eta_lat = 10e-3

[neuron_params]
C_v = 1.0
C_u = 1.0
E_l = -70.0
E_exc = 0.0
E_inh = -75.0
g_l = 0.1
g_den = 2.0
g_exc = 0.3
g_inh = 6.0
a   = 0.3
b   = -58.0
d_int = 25
lam = 0.6

[data_params]
pattern_length = 22
